2024-03-13 20:10:35,852 INFO    MainThread:27736 [wandb_setup.py:_flush():76] Current SDK version is 0.15.11
2024-03-13 20:10:35,852 INFO    MainThread:27736 [wandb_setup.py:_flush():76] Configure stats pid to 27736
2024-03-13 20:10:35,852 INFO    MainThread:27736 [wandb_setup.py:_flush():76] Loading settings from C:\Users\lenovo\.config\wandb\settings
2024-03-13 20:10:35,852 INFO    MainThread:27736 [wandb_setup.py:_flush():76] Loading settings from E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\settings
2024-03-13 20:10:35,852 INFO    MainThread:27736 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-03-13 20:10:35,853 INFO    MainThread:27736 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-03-13 20:10:35,853 INFO    MainThread:27736 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'train.py', 'program_abspath': 'E:\\自动驾驶\\车位检测\\parking-space-Identification-in-different-weather-main\\train.py', 'program': 'E:\\自动驾驶\\车位检测\\parking-space-Identification-in-different-weather-main\\train.py'}
2024-03-13 20:10:35,853 INFO    MainThread:27736 [wandb_init.py:_log_setup():528] Logging user logs to E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_201035-4h9hxv1t\logs\debug.log
2024-03-13 20:10:35,853 INFO    MainThread:27736 [wandb_init.py:_log_setup():529] Logging internal logs to E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_201035-4h9hxv1t\logs\debug-internal.log
2024-03-13 20:10:35,853 INFO    MainThread:27736 [wandb_init.py:init():568] calling init triggers
2024-03-13 20:10:35,853 INFO    MainThread:27736 [wandb_init.py:init():575] wandb.init called with sweep_config: {}
config: {}
2024-03-13 20:10:35,853 INFO    MainThread:27736 [wandb_init.py:init():618] starting backend
2024-03-13 20:10:35,853 INFO    MainThread:27736 [wandb_init.py:init():622] setting up manager
2024-03-13 20:10:35,859 INFO    MainThread:27736 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-03-13 20:10:35,861 INFO    MainThread:27736 [wandb_init.py:init():628] backend started and connected
2024-03-13 20:10:35,867 INFO    MainThread:27736 [wandb_init.py:init():720] updated telemetry
2024-03-13 20:10:35,868 INFO    MainThread:27736 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-03-13 20:12:06,296 ERROR   MainThread:27736 [wandb_init.py:init():779] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-03-13 20:12:08,310 ERROR   MainThread:27736 [wandb_init.py:init():1188] Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "E:\anaconda\lib\site-packages\wandb\sdk\wandb_init.py", line 1170, in init
    run = wi.init()
  File "E:\anaconda\lib\site-packages\wandb\sdk\wandb_init.py", line 785, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-03-13 20:12:10,340 WARNING MsgRouterThr:27736 [router.py:message_loop():77] message_loop has been closed
