2024-03-13 16:18:24,505 INFO    StreamThr :28508 [internal.py:wandb_internal():86] W&B internal server running at pid: 28508, started at: 2024-03-13 16:18:24.504689
2024-03-13 16:18:24,506 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: status
2024-03-13 16:18:24,511 INFO    WriterThread:28508 [datastore.py:open_for_write():85] open: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\run-6nygko79.wandb
2024-03-13 16:18:24,513 DEBUG   SenderThread:28508 [sender.py:send():380] send: header
2024-03-13 16:18:24,513 DEBUG   SenderThread:28508 [sender.py:send():380] send: run
2024-03-13 16:18:25,662 INFO    SenderThread:28508 [dir_watcher.py:__init__():211] watching files in: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files
2024-03-13 16:18:25,662 INFO    SenderThread:28508 [sender.py:_start_run_threads():1122] run started: 6nygko79 with start time 1710317904.505689
2024-03-13 16:18:25,680 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: check_version
2024-03-13 16:18:25,680 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: check_version
2024-03-13 16:18:30,695 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 16:18:30,709 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: run_start
2024-03-13 16:18:30,752 DEBUG   HandlerThread:28508 [system_info.py:__init__():32] System info init
2024-03-13 16:18:30,752 DEBUG   HandlerThread:28508 [system_info.py:__init__():47] System info init done
2024-03-13 16:18:30,752 INFO    HandlerThread:28508 [system_monitor.py:start():181] Starting system monitor
2024-03-13 16:18:30,752 INFO    SystemMonitor:28508 [system_monitor.py:_start():145] Starting system asset monitoring threads
2024-03-13 16:18:30,753 INFO    HandlerThread:28508 [system_monitor.py:probe():201] Collecting system info
2024-03-13 16:18:30,757 INFO    SystemMonitor:28508 [interfaces.py:start():190] Started cpu monitoring
2024-03-13 16:18:30,758 INFO    SystemMonitor:28508 [interfaces.py:start():190] Started disk monitoring
2024-03-13 16:18:30,759 INFO    SystemMonitor:28508 [interfaces.py:start():190] Started gpu monitoring
2024-03-13 16:18:30,759 INFO    SystemMonitor:28508 [interfaces.py:start():190] Started memory monitoring
2024-03-13 16:18:30,774 INFO    SystemMonitor:28508 [interfaces.py:start():190] Started network monitoring
2024-03-13 16:18:30,797 DEBUG   HandlerThread:28508 [system_info.py:probe():196] Probing system
2024-03-13 16:18:30,797 DEBUG   HandlerThread:28508 [system_info.py:probe():244] Probing system done
2024-03-13 16:18:30,797 DEBUG   HandlerThread:28508 [system_monitor.py:probe():210] {'os': 'Windows-10-10.0.22000-SP0', 'python': '3.10.9', 'heartbeatAt': '2024-03-13T08:18:30.797737', 'startedAt': '2024-03-13T08:18:24.490686', 'docker': None, 'cuda': None, 'args': ('--task=P', '--weather=mix'), 'state': 'running', 'program': 'E:\\自动驾驶\\车位检测\\parking-space-Identification-in-different-weather-main\\train.py', 'codePathLocal': 'train.py', 'codePath': 'train.py', 'host': 'LAPTOP-QIVT4NMT', 'username': 'lenovo', 'executable': 'E:\\anaconda\\python.exe', 'cpu_count': 8, 'cpu_count_logical': 16, 'cpu_freq': {'current': 3201.0, 'min': 0.0, 'max': 3201.0}, 'cpu_freq_per_core': [{'current': 3201.0, 'min': 0.0, 'max': 3201.0}], 'disk': {'/': {'total': 465.74511337280273, 'used': 176.68144989013672}}, 'gpu': 'NVIDIA GeForce RTX 3060 Laptop GPU', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3060 Laptop GPU', 'memory_total': 6442450944}], 'memory': {'total': 15.855525970458984}}
2024-03-13 16:18:30,797 INFO    HandlerThread:28508 [system_monitor.py:probe():211] Finished collecting system info
2024-03-13 16:18:30,797 INFO    HandlerThread:28508 [system_monitor.py:probe():214] Publishing system info
2024-03-13 16:18:30,798 DEBUG   HandlerThread:28508 [system_info.py:_save_pip():52] Saving list of pip packages installed into the current environment
2024-03-13 16:18:30,798 DEBUG   HandlerThread:28508 [system_info.py:_save_pip():68] Saving pip packages done
2024-03-13 16:18:30,799 DEBUG   HandlerThread:28508 [system_info.py:_save_conda():75] Saving list of conda packages installed into the current environment
2024-03-13 16:18:30,809 ERROR   gpu       :28508 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:18:31,701 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_created():271] file/dir created: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\conda-environment.yaml
2024-03-13 16:18:31,702 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_created():271] file/dir created: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\requirements.txt
2024-03-13 16:18:32,847 ERROR   gpu       :28508 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:18:34,889 ERROR   gpu       :28508 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:18:36,927 ERROR   gpu       :28508 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:18:37,724 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\conda-environment.yaml
2024-03-13 16:18:37,837 DEBUG   HandlerThread:28508 [system_info.py:_save_conda():87] Saving conda packages done
2024-03-13 16:18:37,838 INFO    HandlerThread:28508 [system_monitor.py:probe():216] Finished publishing system info
2024-03-13 16:18:37,857 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 16:18:37,858 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: keepalive
2024-03-13 16:18:37,858 DEBUG   SenderThread:28508 [sender.py:send():380] send: files
2024-03-13 16:18:37,858 INFO    SenderThread:28508 [sender.py:_save_file():1378] saving file wandb-metadata.json with policy now
2024-03-13 16:18:37,870 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: stop_status
2024-03-13 16:18:37,871 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: stop_status
2024-03-13 16:18:37,872 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 16:18:38,714 DEBUG   SenderThread:28508 [sender.py:send():380] send: telemetry
2024-03-13 16:18:38,728 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\conda-environment.yaml
2024-03-13 16:18:38,729 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_created():271] file/dir created: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\output.log
2024-03-13 16:18:38,729 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_created():271] file/dir created: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\wandb-metadata.json
2024-03-13 16:18:38,965 ERROR   gpu       :28508 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:18:40,732 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 16:18:40,734 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\output.log
2024-03-13 16:18:41,004 ERROR   gpu       :28508 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:18:43,049 ERROR   gpu       :28508 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:18:43,758 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:18:43,759 DEBUG   SenderThread:28508 [sender.py:send():380] send: history
2024-03-13 16:18:43,759 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:18:43,760 INFO    SenderThread:28508 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:18:43,777 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_created():271] file/dir created: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\wandb-summary.json
2024-03-13 16:18:44,790 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\output.log
2024-03-13 16:18:45,092 ERROR   gpu       :28508 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:18:45,699 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:18:45,700 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:18:45,700 DEBUG   SenderThread:28508 [sender.py:send():380] send: history
2024-03-13 16:18:45,701 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:18:45,702 INFO    SenderThread:28508 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:18:45,702 DEBUG   SenderThread:28508 [sender.py:send():380] send: history
2024-03-13 16:18:45,702 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:18:45,703 INFO    SenderThread:28508 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:18:45,805 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\wandb-summary.json
2024-03-13 16:18:46,704 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 16:18:46,815 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\output.log
2024-03-13 16:18:47,130 ERROR   gpu       :28508 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:18:48,384 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:18:48,384 DEBUG   SenderThread:28508 [sender.py:send():380] send: history
2024-03-13 16:18:48,385 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:18:48,385 INFO    SenderThread:28508 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:18:48,821 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\wandb-summary.json
2024-03-13 16:18:49,170 ERROR   gpu       :28508 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:18:49,428 ERROR   wandb-upload_0:28508 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/6nygko79/wandb-metadata.json?Expires=1710404321&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=vIQj78oQEs3JQW54DLm%2F4%2B82Z1znKSOaONnBKMSLby%2BrU6ipT3kL3e7p3HWe8EKT0WIFthGwNhVUyDi6KB9cHJlD1yzz0OextEni1hfeL2rHVylOIcskUvbDhDpgFL8bAGHHVHNT%2BJ8qGtwBI6d1dgNfqGrDSZsD0BFSI1EawEFoa%2B2zqtZVUG%2B5tFKLnIKh9jiqA27hRRjp1oozspiDOX9WY3f9b6oTtFZ2GqRcFp5a3u5UU7P%2Bcr%2BUlLKf4ptZcCtSH6%2F96i6shNDnNFkI5d%2FZMi9Z5MxTROvzJ07OA3sNvcFCC2HIgmj5ueisK%2Bs9j2BurqKTzqRf1D8KapT31Q%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/6nygko79/wandb-metadata.json?Expires=1710404321&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=vIQj78oQEs3JQW54DLm%2F4%2B82Z1znKSOaONnBKMSLby%2BrU6ipT3kL3e7p3HWe8EKT0WIFthGwNhVUyDi6KB9cHJlD1yzz0OextEni1hfeL2rHVylOIcskUvbDhDpgFL8bAGHHVHNT%2BJ8qGtwBI6d1dgNfqGrDSZsD0BFSI1EawEFoa%2B2zqtZVUG%2B5tFKLnIKh9jiqA27hRRjp1oozspiDOX9WY3f9b6oTtFZ2GqRcFp5a3u5UU7P%2Bcr%2BUlLKf4ptZcCtSH6%2F96i6shNDnNFkI5d%2FZMi9Z5MxTROvzJ07OA3sNvcFCC2HIgmj5ueisK%2Bs9j2BurqKTzqRf1D8KapT31Q%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002A76D0E4940>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 16:18:49,429 ERROR   wandb-upload_0:28508 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1319'}
2024-03-13 16:18:49,429 ERROR   wandb-upload_0:28508 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 16:18:50,253 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:18:50,253 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:18:50,254 DEBUG   SenderThread:28508 [sender.py:send():380] send: history
2024-03-13 16:18:50,254 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:18:50,256 INFO    SenderThread:28508 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:18:50,256 DEBUG   SenderThread:28508 [sender.py:send():380] send: history
2024-03-13 16:18:50,256 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:18:50,257 INFO    SenderThread:28508 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:18:50,839 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\output.log
2024-03-13 16:18:50,840 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\wandb-summary.json
2024-03-13 16:18:51,208 ERROR   gpu       :28508 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:18:52,269 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 16:18:52,883 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: stop_status
2024-03-13 16:18:52,883 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 16:18:52,884 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: stop_status
2024-03-13 16:18:52,907 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:18:53,169 DEBUG   SenderThread:28508 [sender.py:send():380] send: history
2024-03-13 16:18:53,170 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:18:53,171 INFO    SenderThread:28508 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:18:53,249 ERROR   gpu       :28508 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:18:53,879 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\wandb-summary.json
2024-03-13 16:18:54,834 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:18:54,835 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:18:54,835 DEBUG   SenderThread:28508 [sender.py:send():380] send: history
2024-03-13 16:18:54,836 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:18:54,836 INFO    SenderThread:28508 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:18:54,837 DEBUG   SenderThread:28508 [sender.py:send():380] send: history
2024-03-13 16:18:54,837 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:18:54,838 INFO    SenderThread:28508 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:18:54,895 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\output.log
2024-03-13 16:18:54,896 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\wandb-summary.json
2024-03-13 16:18:55,289 ERROR   gpu       :28508 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:18:56,913 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\output.log
2024-03-13 16:18:57,314 ERROR   gpu       :28508 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:18:57,511 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 16:18:57,512 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:18:57,856 DEBUG   SenderThread:28508 [sender.py:send():380] send: history
2024-03-13 16:18:57,856 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:18:57,857 INFO    SenderThread:28508 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:18:57,917 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\config.yaml
2024-03-13 16:18:57,918 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\wandb-summary.json
2024-03-13 16:18:58,919 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\output.log
2024-03-13 16:18:59,348 ERROR   gpu       :28508 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:18:59,349 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:18:59,350 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:18:59,350 DEBUG   SenderThread:28508 [sender.py:send():380] send: history
2024-03-13 16:18:59,350 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:18:59,351 INFO    SenderThread:28508 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:18:59,352 DEBUG   SenderThread:28508 [sender.py:send():380] send: history
2024-03-13 16:18:59,352 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:18:59,352 INFO    SenderThread:28508 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:18:59,922 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\wandb-summary.json
2024-03-13 16:19:00,532 ERROR   wandb-upload_0:28508 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/6nygko79/wandb-metadata.json?Expires=1710404321&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=vIQj78oQEs3JQW54DLm%2F4%2B82Z1znKSOaONnBKMSLby%2BrU6ipT3kL3e7p3HWe8EKT0WIFthGwNhVUyDi6KB9cHJlD1yzz0OextEni1hfeL2rHVylOIcskUvbDhDpgFL8bAGHHVHNT%2BJ8qGtwBI6d1dgNfqGrDSZsD0BFSI1EawEFoa%2B2zqtZVUG%2B5tFKLnIKh9jiqA27hRRjp1oozspiDOX9WY3f9b6oTtFZ2GqRcFp5a3u5UU7P%2Bcr%2BUlLKf4ptZcCtSH6%2F96i6shNDnNFkI5d%2FZMi9Z5MxTROvzJ07OA3sNvcFCC2HIgmj5ueisK%2Bs9j2BurqKTzqRf1D8KapT31Q%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/6nygko79/wandb-metadata.json?Expires=1710404321&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=vIQj78oQEs3JQW54DLm%2F4%2B82Z1znKSOaONnBKMSLby%2BrU6ipT3kL3e7p3HWe8EKT0WIFthGwNhVUyDi6KB9cHJlD1yzz0OextEni1hfeL2rHVylOIcskUvbDhDpgFL8bAGHHVHNT%2BJ8qGtwBI6d1dgNfqGrDSZsD0BFSI1EawEFoa%2B2zqtZVUG%2B5tFKLnIKh9jiqA27hRRjp1oozspiDOX9WY3f9b6oTtFZ2GqRcFp5a3u5UU7P%2Bcr%2BUlLKf4ptZcCtSH6%2F96i6shNDnNFkI5d%2FZMi9Z5MxTROvzJ07OA3sNvcFCC2HIgmj5ueisK%2Bs9j2BurqKTzqRf1D8KapT31Q%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002A76D2866B0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 16:19:00,532 ERROR   wandb-upload_0:28508 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1319'}
2024-03-13 16:19:00,532 ERROR   wandb-upload_0:28508 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 16:19:00,924 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\output.log
2024-03-13 16:19:01,434 ERROR   gpu       :28508 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:19:01,981 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:19:01,982 DEBUG   SenderThread:28508 [sender.py:send():380] send: history
2024-03-13 16:19:01,982 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:19:01,983 INFO    SenderThread:28508 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:19:02,951 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\output.log
2024-03-13 16:19:02,952 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\wandb-summary.json
2024-03-13 16:19:02,993 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 16:19:03,455 ERROR   gpu       :28508 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:19:03,835 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:19:03,835 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:19:03,836 DEBUG   SenderThread:28508 [sender.py:send():380] send: history
2024-03-13 16:19:03,836 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:19:03,837 INFO    SenderThread:28508 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:19:03,838 DEBUG   SenderThread:28508 [sender.py:send():380] send: history
2024-03-13 16:19:03,838 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:19:03,838 INFO    SenderThread:28508 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:19:03,965 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\wandb-summary.json
2024-03-13 16:19:04,970 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\output.log
2024-03-13 16:19:05,486 ERROR   gpu       :28508 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:19:06,466 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:19:06,467 DEBUG   SenderThread:28508 [sender.py:send():380] send: history
2024-03-13 16:19:06,467 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:19:06,468 INFO    SenderThread:28508 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:19:06,990 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\output.log
2024-03-13 16:19:06,991 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\wandb-summary.json
2024-03-13 16:19:07,521 ERROR   gpu       :28508 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:19:07,894 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 16:19:07,894 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: stop_status
2024-03-13 16:19:07,895 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: stop_status
2024-03-13 16:19:08,216 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 16:19:08,340 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:19:08,340 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:19:08,341 DEBUG   SenderThread:28508 [sender.py:send():380] send: history
2024-03-13 16:19:08,342 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:19:08,342 INFO    SenderThread:28508 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:19:08,343 DEBUG   SenderThread:28508 [sender.py:send():380] send: history
2024-03-13 16:19:08,343 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:19:08,344 INFO    SenderThread:28508 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:19:09,023 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\output.log
2024-03-13 16:19:09,024 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\wandb-summary.json
2024-03-13 16:19:09,546 ERROR   gpu       :28508 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:19:10,978 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:19:10,979 DEBUG   SenderThread:28508 [sender.py:send():380] send: history
2024-03-13 16:19:10,979 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:19:10,980 INFO    SenderThread:28508 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:19:11,038 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\wandb-summary.json
2024-03-13 16:19:11,583 ERROR   gpu       :28508 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:19:12,840 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:19:12,840 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:19:12,841 DEBUG   SenderThread:28508 [sender.py:send():380] send: history
2024-03-13 16:19:12,842 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:19:12,843 INFO    SenderThread:28508 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:19:12,843 DEBUG   SenderThread:28508 [sender.py:send():380] send: history
2024-03-13 16:19:12,843 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:19:12,844 INFO    SenderThread:28508 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:19:13,043 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\output.log
2024-03-13 16:19:13,043 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\wandb-summary.json
2024-03-13 16:19:13,603 ERROR   gpu       :28508 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:19:13,726 ERROR   wandb-upload_0:28508 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/6nygko79/wandb-metadata.json?Expires=1710404321&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=vIQj78oQEs3JQW54DLm%2F4%2B82Z1znKSOaONnBKMSLby%2BrU6ipT3kL3e7p3HWe8EKT0WIFthGwNhVUyDi6KB9cHJlD1yzz0OextEni1hfeL2rHVylOIcskUvbDhDpgFL8bAGHHVHNT%2BJ8qGtwBI6d1dgNfqGrDSZsD0BFSI1EawEFoa%2B2zqtZVUG%2B5tFKLnIKh9jiqA27hRRjp1oozspiDOX9WY3f9b6oTtFZ2GqRcFp5a3u5UU7P%2Bcr%2BUlLKf4ptZcCtSH6%2F96i6shNDnNFkI5d%2FZMi9Z5MxTROvzJ07OA3sNvcFCC2HIgmj5ueisK%2Bs9j2BurqKTzqRf1D8KapT31Q%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/6nygko79/wandb-metadata.json?Expires=1710404321&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=vIQj78oQEs3JQW54DLm%2F4%2B82Z1znKSOaONnBKMSLby%2BrU6ipT3kL3e7p3HWe8EKT0WIFthGwNhVUyDi6KB9cHJlD1yzz0OextEni1hfeL2rHVylOIcskUvbDhDpgFL8bAGHHVHNT%2BJ8qGtwBI6d1dgNfqGrDSZsD0BFSI1EawEFoa%2B2zqtZVUG%2B5tFKLnIKh9jiqA27hRRjp1oozspiDOX9WY3f9b6oTtFZ2GqRcFp5a3u5UU7P%2Bcr%2BUlLKf4ptZcCtSH6%2F96i6shNDnNFkI5d%2FZMi9Z5MxTROvzJ07OA3sNvcFCC2HIgmj5ueisK%2Bs9j2BurqKTzqRf1D8KapT31Q%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002A76D286AD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2024-03-13 16:19:13,726 ERROR   wandb-upload_0:28508 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1319'}
2024-03-13 16:19:13,726 ERROR   wandb-upload_0:28508 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 16:19:13,726 INFO    wandb-upload_0:28508 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "E:\anaconda\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "E:\anaconda\lib\site-packages\urllib3\util\connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "E:\anaconda\lib\socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "E:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "E:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "E:\anaconda\lib\site-packages\urllib3\connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "E:\anaconda\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000002A76D286AD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\anaconda\lib\site-packages\requests\adapters.py", line 487, in send
    resp = conn.urlopen(
  File "E:\anaconda\lib\site-packages\urllib3\connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "E:\anaconda\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/6nygko79/wandb-metadata.json?Expires=1710404321&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=vIQj78oQEs3JQW54DLm%2F4%2B82Z1znKSOaONnBKMSLby%2BrU6ipT3kL3e7p3HWe8EKT0WIFthGwNhVUyDi6KB9cHJlD1yzz0OextEni1hfeL2rHVylOIcskUvbDhDpgFL8bAGHHVHNT%2BJ8qGtwBI6d1dgNfqGrDSZsD0BFSI1EawEFoa%2B2zqtZVUG%2B5tFKLnIKh9jiqA27hRRjp1oozspiDOX9WY3f9b6oTtFZ2GqRcFp5a3u5UU7P%2Bcr%2BUlLKf4ptZcCtSH6%2F96i6shNDnNFkI5d%2FZMi9Z5MxTROvzJ07OA3sNvcFCC2HIgmj5ueisK%2Bs9j2BurqKTzqRf1D8KapT31Q%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002A76D286AD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\anaconda\lib\site-packages\wandb\sdk\internal\internal_api.py", line 2549, in upload_file
    response = self._upload_file_session.put(
  File "E:\anaconda\lib\site-packages\requests\sessions.py", line 647, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "E:\anaconda\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\anaconda\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "E:\anaconda\lib\site-packages\requests\adapters.py", line 520, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/6nygko79/wandb-metadata.json?Expires=1710404321&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=vIQj78oQEs3JQW54DLm%2F4%2B82Z1znKSOaONnBKMSLby%2BrU6ipT3kL3e7p3HWe8EKT0WIFthGwNhVUyDi6KB9cHJlD1yzz0OextEni1hfeL2rHVylOIcskUvbDhDpgFL8bAGHHVHNT%2BJ8qGtwBI6d1dgNfqGrDSZsD0BFSI1EawEFoa%2B2zqtZVUG%2B5tFKLnIKh9jiqA27hRRjp1oozspiDOX9WY3f9b6oTtFZ2GqRcFp5a3u5UU7P%2Bcr%2BUlLKf4ptZcCtSH6%2F96i6shNDnNFkI5d%2FZMi9Z5MxTROvzJ07OA3sNvcFCC2HIgmj5ueisK%2Bs9j2BurqKTzqRf1D8KapT31Q%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002A76D286AD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\anaconda\lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "E:\anaconda\lib\site-packages\wandb\sdk\internal\internal_api.py", line 2580, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "E:\anaconda\lib\site-packages\wandb\sdk\internal\internal_api.py", line 2549, in upload_file
    response = self._upload_file_session.put(
  File "E:\anaconda\lib\site-packages\requests\sessions.py", line 647, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "E:\anaconda\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\anaconda\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "E:\anaconda\lib\site-packages\requests\adapters.py", line 520, in send
    raise ConnectionError(e, request=request)
wandb.sdk.lib.retry.TransientError: None
2024-03-13 16:19:13,854 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 16:19:15,048 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\output.log
2024-03-13 16:19:15,466 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:19:15,467 DEBUG   SenderThread:28508 [sender.py:send():380] send: history
2024-03-13 16:19:15,467 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:19:15,468 INFO    SenderThread:28508 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:19:15,633 ERROR   gpu       :28508 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:19:16,050 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\wandb-summary.json
2024-03-13 16:19:17,052 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\output.log
2024-03-13 16:19:17,363 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:19:17,363 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:19:17,364 DEBUG   SenderThread:28508 [sender.py:send():380] send: history
2024-03-13 16:19:17,364 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:19:17,365 INFO    SenderThread:28508 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:19:17,366 DEBUG   SenderThread:28508 [sender.py:send():380] send: history
2024-03-13 16:19:17,366 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:19:17,366 INFO    SenderThread:28508 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:19:17,671 ERROR   gpu       :28508 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:19:18,053 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\wandb-summary.json
2024-03-13 16:19:19,060 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\output.log
2024-03-13 16:19:19,385 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 16:19:19,703 ERROR   gpu       :28508 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:19:19,993 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:19:19,993 DEBUG   SenderThread:28508 [sender.py:send():380] send: history
2024-03-13 16:19:19,993 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:19:19,994 INFO    SenderThread:28508 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:19:20,069 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\wandb-summary.json
2024-03-13 16:19:21,075 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\output.log
2024-03-13 16:19:21,734 ERROR   gpu       :28508 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:19:21,901 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:19:21,902 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:19:21,903 DEBUG   SenderThread:28508 [sender.py:send():380] send: history
2024-03-13 16:19:21,903 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:19:21,904 INFO    SenderThread:28508 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:19:21,904 DEBUG   SenderThread:28508 [sender.py:send():380] send: history
2024-03-13 16:19:21,904 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:19:21,905 INFO    SenderThread:28508 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:19:22,087 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\wandb-summary.json
2024-03-13 16:19:22,911 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: stop_status
2024-03-13 16:19:22,912 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 16:19:22,912 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: stop_status
2024-03-13 16:19:23,102 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\output.log
2024-03-13 16:19:23,767 ERROR   gpu       :28508 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:19:24,527 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 16:19:24,527 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:19:24,528 DEBUG   SenderThread:28508 [sender.py:send():380] send: history
2024-03-13 16:19:24,528 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:19:24,529 INFO    SenderThread:28508 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:19:25,109 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\wandb-summary.json
2024-03-13 16:19:25,809 ERROR   gpu       :28508 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:19:26,422 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:19:26,422 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:19:26,423 DEBUG   SenderThread:28508 [sender.py:send():380] send: history
2024-03-13 16:19:26,424 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:19:26,424 INFO    SenderThread:28508 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:19:26,425 DEBUG   SenderThread:28508 [sender.py:send():380] send: history
2024-03-13 16:19:26,425 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:19:26,425 INFO    SenderThread:28508 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:19:27,117 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\output.log
2024-03-13 16:19:27,118 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\wandb-summary.json
2024-03-13 16:19:27,849 ERROR   gpu       :28508 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:19:29,085 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:19:29,085 DEBUG   SenderThread:28508 [sender.py:send():380] send: history
2024-03-13 16:19:29,085 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:19:29,086 INFO    SenderThread:28508 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:19:29,122 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\wandb-summary.json
2024-03-13 16:19:29,886 ERROR   gpu       :28508 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:19:30,092 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 16:19:30,778 DEBUG   SystemMonitor:28508 [system_monitor.py:_start():159] Starting system metrics aggregation loop
2024-03-13 16:19:30,779 DEBUG   SenderThread:28508 [sender.py:send():380] send: stats
2024-03-13 16:19:30,901 ERROR   wandb-upload_0:28508 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/6nygko79/wandb-metadata.json?Expires=1710404321&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=vIQj78oQEs3JQW54DLm%2F4%2B82Z1znKSOaONnBKMSLby%2BrU6ipT3kL3e7p3HWe8EKT0WIFthGwNhVUyDi6KB9cHJlD1yzz0OextEni1hfeL2rHVylOIcskUvbDhDpgFL8bAGHHVHNT%2BJ8qGtwBI6d1dgNfqGrDSZsD0BFSI1EawEFoa%2B2zqtZVUG%2B5tFKLnIKh9jiqA27hRRjp1oozspiDOX9WY3f9b6oTtFZ2GqRcFp5a3u5UU7P%2Bcr%2BUlLKf4ptZcCtSH6%2F96i6shNDnNFkI5d%2FZMi9Z5MxTROvzJ07OA3sNvcFCC2HIgmj5ueisK%2Bs9j2BurqKTzqRf1D8KapT31Q%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/6nygko79/wandb-metadata.json?Expires=1710404321&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=vIQj78oQEs3JQW54DLm%2F4%2B82Z1znKSOaONnBKMSLby%2BrU6ipT3kL3e7p3HWe8EKT0WIFthGwNhVUyDi6KB9cHJlD1yzz0OextEni1hfeL2rHVylOIcskUvbDhDpgFL8bAGHHVHNT%2BJ8qGtwBI6d1dgNfqGrDSZsD0BFSI1EawEFoa%2B2zqtZVUG%2B5tFKLnIKh9jiqA27hRRjp1oozspiDOX9WY3f9b6oTtFZ2GqRcFp5a3u5UU7P%2Bcr%2BUlLKf4ptZcCtSH6%2F96i6shNDnNFkI5d%2FZMi9Z5MxTROvzJ07OA3sNvcFCC2HIgmj5ueisK%2Bs9j2BurqKTzqRf1D8KapT31Q%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002A76D285150>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 16:19:30,901 ERROR   wandb-upload_0:28508 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1319'}
2024-03-13 16:19:30,901 ERROR   wandb-upload_0:28508 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 16:19:31,006 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:19:31,007 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:19:31,008 DEBUG   SenderThread:28508 [sender.py:send():380] send: history
2024-03-13 16:19:31,008 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:19:31,009 INFO    SenderThread:28508 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:19:31,010 DEBUG   SenderThread:28508 [sender.py:send():380] send: history
2024-03-13 16:19:31,010 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:19:31,010 INFO    SenderThread:28508 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:19:31,128 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\output.log
2024-03-13 16:19:31,129 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\wandb-summary.json
2024-03-13 16:19:31,978 ERROR   gpu       :28508 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:19:33,151 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\output.log
2024-03-13 16:19:33,662 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:19:33,663 DEBUG   SenderThread:28508 [sender.py:send():380] send: history
2024-03-13 16:19:33,663 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:19:33,664 INFO    SenderThread:28508 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:19:34,016 ERROR   gpu       :28508 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:19:34,167 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\wandb-summary.json
2024-03-13 16:19:35,170 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\output.log
2024-03-13 16:19:35,556 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 16:19:35,556 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:19:35,557 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:19:35,557 DEBUG   SenderThread:28508 [sender.py:send():380] send: history
2024-03-13 16:19:35,558 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:19:35,558 INFO    SenderThread:28508 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:19:35,559 DEBUG   SenderThread:28508 [sender.py:send():380] send: history
2024-03-13 16:19:35,559 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:19:35,560 INFO    SenderThread:28508 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:19:36,044 ERROR   gpu       :28508 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:19:36,172 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\wandb-summary.json
2024-03-13 16:19:37,176 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\output.log
2024-03-13 16:19:37,925 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 16:19:37,925 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: stop_status
2024-03-13 16:19:37,926 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: stop_status
2024-03-13 16:19:38,073 ERROR   gpu       :28508 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:19:38,192 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:19:38,259 DEBUG   SenderThread:28508 [sender.py:send():380] send: history
2024-03-13 16:19:38,259 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:19:38,260 INFO    SenderThread:28508 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:19:39,195 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\output.log
2024-03-13 16:19:39,196 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\wandb-summary.json
2024-03-13 16:19:40,068 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:19:40,069 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:19:40,070 DEBUG   SenderThread:28508 [sender.py:send():380] send: history
2024-03-13 16:19:40,070 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:19:40,071 INFO    SenderThread:28508 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:19:40,071 DEBUG   SenderThread:28508 [sender.py:send():380] send: history
2024-03-13 16:19:40,071 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:19:40,072 INFO    SenderThread:28508 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:19:40,106 ERROR   gpu       :28508 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:19:40,201 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\wandb-summary.json
2024-03-13 16:19:41,074 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 16:19:41,217 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\output.log
2024-03-13 16:19:42,136 ERROR   gpu       :28508 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:19:42,712 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:19:42,713 DEBUG   SenderThread:28508 [sender.py:send():380] send: history
2024-03-13 16:19:42,713 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:19:42,713 INFO    SenderThread:28508 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:19:43,244 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\output.log
2024-03-13 16:19:43,245 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\wandb-summary.json
2024-03-13 16:19:44,165 ERROR   gpu       :28508 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:19:44,654 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:19:44,655 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:19:44,656 DEBUG   SenderThread:28508 [sender.py:send():380] send: history
2024-03-13 16:19:44,656 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:19:44,657 INFO    SenderThread:28508 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:19:44,657 DEBUG   SenderThread:28508 [sender.py:send():380] send: history
2024-03-13 16:19:44,657 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:19:44,658 INFO    SenderThread:28508 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:19:45,272 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\output.log
2024-03-13 16:19:45,273 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\wandb-summary.json
2024-03-13 16:19:46,204 ERROR   gpu       :28508 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:19:46,682 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 16:19:47,284 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:19:47,284 DEBUG   SenderThread:28508 [sender.py:send():380] send: history
2024-03-13 16:19:47,285 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:19:47,285 INFO    SenderThread:28508 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:19:47,288 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\wandb-summary.json
2024-03-13 16:19:48,240 ERROR   gpu       :28508 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:19:49,153 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:19:49,153 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:19:49,154 DEBUG   SenderThread:28508 [sender.py:send():380] send: history
2024-03-13 16:19:49,155 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:19:49,155 INFO    SenderThread:28508 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:19:49,156 DEBUG   SenderThread:28508 [sender.py:send():380] send: history
2024-03-13 16:19:49,156 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:19:49,156 INFO    SenderThread:28508 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:19:49,306 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\output.log
2024-03-13 16:19:49,307 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\wandb-summary.json
2024-03-13 16:19:50,278 ERROR   gpu       :28508 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:19:51,315 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\output.log
2024-03-13 16:19:51,775 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 16:19:51,775 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:19:51,776 DEBUG   SenderThread:28508 [sender.py:send():380] send: history
2024-03-13 16:19:51,776 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:19:51,777 INFO    SenderThread:28508 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:19:52,312 ERROR   gpu       :28508 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:19:52,317 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\wandb-summary.json
2024-03-13 16:19:52,733 ERROR   wandb-upload_0:28508 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/6nygko79/wandb-metadata.json?Expires=1710404321&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=vIQj78oQEs3JQW54DLm%2F4%2B82Z1znKSOaONnBKMSLby%2BrU6ipT3kL3e7p3HWe8EKT0WIFthGwNhVUyDi6KB9cHJlD1yzz0OextEni1hfeL2rHVylOIcskUvbDhDpgFL8bAGHHVHNT%2BJ8qGtwBI6d1dgNfqGrDSZsD0BFSI1EawEFoa%2B2zqtZVUG%2B5tFKLnIKh9jiqA27hRRjp1oozspiDOX9WY3f9b6oTtFZ2GqRcFp5a3u5UU7P%2Bcr%2BUlLKf4ptZcCtSH6%2F96i6shNDnNFkI5d%2FZMi9Z5MxTROvzJ07OA3sNvcFCC2HIgmj5ueisK%2Bs9j2BurqKTzqRf1D8KapT31Q%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/6nygko79/wandb-metadata.json?Expires=1710404321&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=vIQj78oQEs3JQW54DLm%2F4%2B82Z1znKSOaONnBKMSLby%2BrU6ipT3kL3e7p3HWe8EKT0WIFthGwNhVUyDi6KB9cHJlD1yzz0OextEni1hfeL2rHVylOIcskUvbDhDpgFL8bAGHHVHNT%2BJ8qGtwBI6d1dgNfqGrDSZsD0BFSI1EawEFoa%2B2zqtZVUG%2B5tFKLnIKh9jiqA27hRRjp1oozspiDOX9WY3f9b6oTtFZ2GqRcFp5a3u5UU7P%2Bcr%2BUlLKf4ptZcCtSH6%2F96i6shNDnNFkI5d%2FZMi9Z5MxTROvzJ07OA3sNvcFCC2HIgmj5ueisK%2Bs9j2BurqKTzqRf1D8KapT31Q%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002A76D286D40>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 16:19:52,733 ERROR   wandb-upload_0:28508 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1319'}
2024-03-13 16:19:52,733 ERROR   wandb-upload_0:28508 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 16:19:52,938 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 16:19:52,938 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: stop_status
2024-03-13 16:19:52,939 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: stop_status
2024-03-13 16:19:53,321 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\output.log
2024-03-13 16:19:53,704 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:19:53,705 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:19:53,705 DEBUG   SenderThread:28508 [sender.py:send():380] send: history
2024-03-13 16:19:53,706 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:19:53,707 INFO    SenderThread:28508 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:19:53,707 DEBUG   SenderThread:28508 [sender.py:send():380] send: history
2024-03-13 16:19:53,707 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:19:53,708 INFO    SenderThread:28508 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:19:54,338 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\wandb-summary.json
2024-03-13 16:19:54,354 ERROR   gpu       :28508 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:19:55,340 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\output.log
2024-03-13 16:19:56,318 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:19:56,319 DEBUG   SenderThread:28508 [sender.py:send():380] send: history
2024-03-13 16:19:56,319 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:19:56,320 INFO    SenderThread:28508 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:19:56,372 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\wandb-summary.json
2024-03-13 16:19:56,390 ERROR   gpu       :28508 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:19:57,328 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 16:19:57,377 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\output.log
2024-03-13 16:19:58,208 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:19:58,209 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:19:58,209 DEBUG   SenderThread:28508 [sender.py:send():380] send: history
2024-03-13 16:19:58,210 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:19:58,210 INFO    SenderThread:28508 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:19:58,211 DEBUG   SenderThread:28508 [sender.py:send():380] send: history
2024-03-13 16:19:58,211 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:19:58,212 INFO    SenderThread:28508 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:19:58,408 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\wandb-summary.json
2024-03-13 16:19:58,429 ERROR   gpu       :28508 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:19:59,417 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\output.log
2024-03-13 16:20:00,468 ERROR   gpu       :28508 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:20:00,785 DEBUG   SenderThread:28508 [sender.py:send():380] send: stats
2024-03-13 16:20:00,853 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:20:00,853 DEBUG   SenderThread:28508 [sender.py:send():380] send: history
2024-03-13 16:20:00,854 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:20:00,854 INFO    SenderThread:28508 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:20:01,454 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\wandb-summary.json
2024-03-13 16:20:02,555 ERROR   gpu       :28508 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:20:02,773 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 16:20:02,773 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:20:02,774 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:20:02,775 DEBUG   SenderThread:28508 [sender.py:send():380] send: history
2024-03-13 16:20:02,775 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:20:02,776 INFO    SenderThread:28508 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:20:02,776 DEBUG   SenderThread:28508 [sender.py:send():380] send: history
2024-03-13 16:20:02,776 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:20:02,777 INFO    SenderThread:28508 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:20:03,496 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\output.log
2024-03-13 16:20:03,496 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\wandb-summary.json
2024-03-13 16:20:04,572 ERROR   gpu       :28508 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:20:05,430 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:20:05,431 DEBUG   SenderThread:28508 [sender.py:send():380] send: history
2024-03-13 16:20:05,431 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:20:05,431 INFO    SenderThread:28508 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:20:05,529 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\output.log
2024-03-13 16:20:05,530 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\wandb-summary.json
2024-03-13 16:20:06,594 ERROR   gpu       :28508 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:20:07,343 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:20:07,344 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:20:07,344 DEBUG   SenderThread:28508 [sender.py:send():380] send: history
2024-03-13 16:20:07,345 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:20:07,346 INFO    SenderThread:28508 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:20:07,346 DEBUG   SenderThread:28508 [sender.py:send():380] send: history
2024-03-13 16:20:07,346 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:20:07,347 INFO    SenderThread:28508 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:20:07,564 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\output.log
2024-03-13 16:20:07,564 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\wandb-summary.json
2024-03-13 16:20:07,928 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 16:20:07,928 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: internal_messages
2024-03-13 16:20:07,929 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: stop_status
2024-03-13 16:20:07,929 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: stop_status
2024-03-13 16:20:08,612 ERROR   gpu       :28508 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:20:09,594 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\output.log
2024-03-13 16:20:10,006 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:20:10,007 DEBUG   SenderThread:28508 [sender.py:send():380] send: history
2024-03-13 16:20:10,007 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:20:10,008 INFO    SenderThread:28508 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:20:10,625 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\wandb-summary.json
2024-03-13 16:20:10,646 ERROR   gpu       :28508 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-13 16:20:11,629 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\output.log
2024-03-13 16:20:11,911 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:20:11,911 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: partial_history
2024-03-13 16:20:11,912 DEBUG   SenderThread:28508 [sender.py:send():380] send: history
2024-03-13 16:20:11,913 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:20:11,913 INFO    SenderThread:28508 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:20:11,914 DEBUG   SenderThread:28508 [sender.py:send():380] send: history
2024-03-13 16:20:11,914 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: summary_record
2024-03-13 16:20:11,915 INFO    SenderThread:28508 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:20:12,063 DEBUG   SenderThread:28508 [sender.py:send():380] send: exit
2024-03-13 16:20:12,063 INFO    SenderThread:28508 [sender.py:send_exit():585] handling exit code: 0
2024-03-13 16:20:12,063 INFO    SenderThread:28508 [sender.py:send_exit():587] handling runtime: 101
2024-03-13 16:20:12,064 INFO    SenderThread:28508 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:20:12,064 INFO    SenderThread:28508 [sender.py:send_exit():593] send defer
2024-03-13 16:20:12,065 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: defer
2024-03-13 16:20:12,065 INFO    HandlerThread:28508 [handler.py:handle_request_defer():170] handle defer: 0
2024-03-13 16:20:12,065 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: defer
2024-03-13 16:20:12,065 INFO    SenderThread:28508 [sender.py:send_request_defer():609] handle sender defer: 0
2024-03-13 16:20:12,065 INFO    SenderThread:28508 [sender.py:transition_state():613] send defer: 1
2024-03-13 16:20:12,065 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: defer
2024-03-13 16:20:12,065 INFO    HandlerThread:28508 [handler.py:handle_request_defer():170] handle defer: 1
2024-03-13 16:20:12,065 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: defer
2024-03-13 16:20:12,065 INFO    SenderThread:28508 [sender.py:send_request_defer():609] handle sender defer: 1
2024-03-13 16:20:12,065 INFO    SenderThread:28508 [sender.py:transition_state():613] send defer: 2
2024-03-13 16:20:12,065 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: defer
2024-03-13 16:20:12,066 INFO    HandlerThread:28508 [handler.py:handle_request_defer():170] handle defer: 2
2024-03-13 16:20:12,066 INFO    HandlerThread:28508 [system_monitor.py:finish():190] Stopping system monitor
2024-03-13 16:20:12,066 DEBUG   SystemMonitor:28508 [system_monitor.py:_start():166] Finished system metrics aggregation loop
2024-03-13 16:20:12,073 DEBUG   SystemMonitor:28508 [system_monitor.py:_start():170] Publishing last batch of metrics
2024-03-13 16:20:12,073 INFO    HandlerThread:28508 [interfaces.py:finish():202] Joined cpu monitor
2024-03-13 16:20:12,074 INFO    HandlerThread:28508 [interfaces.py:finish():202] Joined disk monitor
2024-03-13 16:20:12,113 INFO    HandlerThread:28508 [interfaces.py:finish():202] Joined gpu monitor
2024-03-13 16:20:12,114 INFO    HandlerThread:28508 [interfaces.py:finish():202] Joined memory monitor
2024-03-13 16:20:12,114 INFO    HandlerThread:28508 [interfaces.py:finish():202] Joined network monitor
2024-03-13 16:20:12,114 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: defer
2024-03-13 16:20:12,115 INFO    SenderThread:28508 [sender.py:send_request_defer():609] handle sender defer: 2
2024-03-13 16:20:12,115 INFO    SenderThread:28508 [sender.py:transition_state():613] send defer: 3
2024-03-13 16:20:12,115 DEBUG   SenderThread:28508 [sender.py:send():380] send: stats
2024-03-13 16:20:12,115 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: defer
2024-03-13 16:20:12,115 INFO    HandlerThread:28508 [handler.py:handle_request_defer():170] handle defer: 3
2024-03-13 16:20:12,115 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: defer
2024-03-13 16:20:12,115 INFO    SenderThread:28508 [sender.py:send_request_defer():609] handle sender defer: 3
2024-03-13 16:20:12,115 INFO    SenderThread:28508 [sender.py:transition_state():613] send defer: 4
2024-03-13 16:20:12,116 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: defer
2024-03-13 16:20:12,116 INFO    HandlerThread:28508 [handler.py:handle_request_defer():170] handle defer: 4
2024-03-13 16:20:12,116 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: defer
2024-03-13 16:20:12,116 INFO    SenderThread:28508 [sender.py:send_request_defer():609] handle sender defer: 4
2024-03-13 16:20:12,116 INFO    SenderThread:28508 [sender.py:transition_state():613] send defer: 5
2024-03-13 16:20:12,116 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: defer
2024-03-13 16:20:12,116 INFO    HandlerThread:28508 [handler.py:handle_request_defer():170] handle defer: 5
2024-03-13 16:20:12,117 DEBUG   SenderThread:28508 [sender.py:send():380] send: summary
2024-03-13 16:20:12,117 INFO    SenderThread:28508 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2024-03-13 16:20:12,118 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: defer
2024-03-13 16:20:12,118 INFO    SenderThread:28508 [sender.py:send_request_defer():609] handle sender defer: 5
2024-03-13 16:20:12,118 INFO    SenderThread:28508 [sender.py:transition_state():613] send defer: 6
2024-03-13 16:20:12,118 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: defer
2024-03-13 16:20:12,118 INFO    HandlerThread:28508 [handler.py:handle_request_defer():170] handle defer: 6
2024-03-13 16:20:12,118 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: defer
2024-03-13 16:20:12,118 INFO    SenderThread:28508 [sender.py:send_request_defer():609] handle sender defer: 6
2024-03-13 16:20:12,118 INFO    SenderThread:28508 [sender.py:transition_state():613] send defer: 7
2024-03-13 16:20:12,119 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 16:20:12,119 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: defer
2024-03-13 16:20:12,119 INFO    HandlerThread:28508 [handler.py:handle_request_defer():170] handle defer: 7
2024-03-13 16:20:12,119 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: defer
2024-03-13 16:20:12,119 INFO    SenderThread:28508 [sender.py:send_request_defer():609] handle sender defer: 7
2024-03-13 16:20:12,642 INFO    Thread-12 :28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\wandb-summary.json
2024-03-13 16:20:13,069 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:20:13,070 INFO    SenderThread:28508 [sender.py:transition_state():613] send defer: 8
2024-03-13 16:20:13,070 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:20:13,070 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: defer
2024-03-13 16:20:13,071 INFO    HandlerThread:28508 [handler.py:handle_request_defer():170] handle defer: 8
2024-03-13 16:20:13,071 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: defer
2024-03-13 16:20:13,071 INFO    SenderThread:28508 [sender.py:send_request_defer():609] handle sender defer: 8
2024-03-13 16:20:13,071 INFO    SenderThread:28508 [job_builder.py:build():281] Attempting to build job artifact
2024-03-13 16:20:13,072 INFO    SenderThread:28508 [job_builder.py:_get_source_type():404] no source found
2024-03-13 16:20:13,072 INFO    SenderThread:28508 [sender.py:transition_state():613] send defer: 9
2024-03-13 16:20:13,072 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: defer
2024-03-13 16:20:13,072 INFO    HandlerThread:28508 [handler.py:handle_request_defer():170] handle defer: 9
2024-03-13 16:20:13,072 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: defer
2024-03-13 16:20:13,072 INFO    SenderThread:28508 [sender.py:send_request_defer():609] handle sender defer: 9
2024-03-13 16:20:13,072 INFO    SenderThread:28508 [dir_watcher.py:finish():358] shutting down directory watcher
2024-03-13 16:20:13,656 INFO    SenderThread:28508 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\output.log
2024-03-13 16:20:13,656 INFO    SenderThread:28508 [dir_watcher.py:finish():388] scan: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files
2024-03-13 16:20:13,657 INFO    SenderThread:28508 [dir_watcher.py:finish():402] scan save: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\conda-environment.yaml conda-environment.yaml
2024-03-13 16:20:13,657 INFO    SenderThread:28508 [dir_watcher.py:finish():402] scan save: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\config.yaml config.yaml
2024-03-13 16:20:13,659 INFO    SenderThread:28508 [dir_watcher.py:finish():402] scan save: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\output.log output.log
2024-03-13 16:20:13,662 INFO    SenderThread:28508 [dir_watcher.py:finish():402] scan save: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\requirements.txt requirements.txt
2024-03-13 16:20:13,664 INFO    SenderThread:28508 [dir_watcher.py:finish():402] scan save: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\wandb-metadata.json wandb-metadata.json
2024-03-13 16:20:13,665 INFO    SenderThread:28508 [dir_watcher.py:finish():402] scan save: E:\自动驾驶\车位检测\parking-space-Identification-in-different-weather-main\wandb\run-20240313_161824-6nygko79\files\wandb-summary.json wandb-summary.json
2024-03-13 16:20:13,666 INFO    SenderThread:28508 [sender.py:transition_state():613] send defer: 10
2024-03-13 16:20:13,667 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: defer
2024-03-13 16:20:13,667 INFO    HandlerThread:28508 [handler.py:handle_request_defer():170] handle defer: 10
2024-03-13 16:20:13,668 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: defer
2024-03-13 16:20:13,669 INFO    SenderThread:28508 [sender.py:send_request_defer():609] handle sender defer: 10
2024-03-13 16:20:13,669 INFO    SenderThread:28508 [file_pusher.py:finish():175] shutting down file pusher
2024-03-13 16:20:14,076 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:20:14,077 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:20:15,083 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:20:15,083 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:20:16,084 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:20:16,085 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:20:17,099 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:20:17,099 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:20:18,113 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 16:20:18,113 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:20:18,114 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:20:19,116 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:20:19,116 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:20:20,125 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:20:20,126 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:20:21,129 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:20:21,130 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:20:22,137 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:20:22,138 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:20:23,148 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 16:20:23,148 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:20:23,149 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:20:23,563 ERROR   wandb-upload_0:28508 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/6nygko79/wandb-metadata.json?Expires=1710404321&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=vIQj78oQEs3JQW54DLm%2F4%2B82Z1znKSOaONnBKMSLby%2BrU6ipT3kL3e7p3HWe8EKT0WIFthGwNhVUyDi6KB9cHJlD1yzz0OextEni1hfeL2rHVylOIcskUvbDhDpgFL8bAGHHVHNT%2BJ8qGtwBI6d1dgNfqGrDSZsD0BFSI1EawEFoa%2B2zqtZVUG%2B5tFKLnIKh9jiqA27hRRjp1oozspiDOX9WY3f9b6oTtFZ2GqRcFp5a3u5UU7P%2Bcr%2BUlLKf4ptZcCtSH6%2F96i6shNDnNFkI5d%2FZMi9Z5MxTROvzJ07OA3sNvcFCC2HIgmj5ueisK%2Bs9j2BurqKTzqRf1D8KapT31Q%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/6nygko79/wandb-metadata.json?Expires=1710404321&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=vIQj78oQEs3JQW54DLm%2F4%2B82Z1znKSOaONnBKMSLby%2BrU6ipT3kL3e7p3HWe8EKT0WIFthGwNhVUyDi6KB9cHJlD1yzz0OextEni1hfeL2rHVylOIcskUvbDhDpgFL8bAGHHVHNT%2BJ8qGtwBI6d1dgNfqGrDSZsD0BFSI1EawEFoa%2B2zqtZVUG%2B5tFKLnIKh9jiqA27hRRjp1oozspiDOX9WY3f9b6oTtFZ2GqRcFp5a3u5UU7P%2Bcr%2BUlLKf4ptZcCtSH6%2F96i6shNDnNFkI5d%2FZMi9Z5MxTROvzJ07OA3sNvcFCC2HIgmj5ueisK%2Bs9j2BurqKTzqRf1D8KapT31Q%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002A76D2872B0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 16:20:23,563 ERROR   wandb-upload_0:28508 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1319'}
2024-03-13 16:20:23,563 ERROR   wandb-upload_0:28508 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 16:20:24,160 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:20:24,160 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:20:25,172 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:20:25,173 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:20:25,934 ERROR   wandb-upload_1:28508 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/6nygko79/conda-environment.yaml?Expires=1710404416&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=oYfY2owGLBgHc4mlWqPcY9u9b7kEb4nOCUwO0IFm638lHHG4BhRGC%2BNcQpoy1a0z4fi2seOaRJfSo%2BM734%2FrNnpWq74gojyt2zMm86h9LCTH3n84acBOxfQFM8xWdkopmeoclz63VjJTRaW%2F%2Be1BbM2W9Ty%2Fzx9Q3kEVS3PU0EzCYZvz44n1OGm8gGKbgbPE0KASKKtHch%2BYdhyQb4vp0avy2%2BICyEeMe%2F%2FVjVA5rVd5QLt6HeXsQ94Knb4BCdVVNS49p0OI8jHk5eMmqnh7GdsxmcfbEjoMDOhGDitoDhAV7OWvZfpNe19vCosIqhr5rEJQwPVS%2B%2BT8y7GBAz19zg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/6nygko79/conda-environment.yaml?Expires=1710404416&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=oYfY2owGLBgHc4mlWqPcY9u9b7kEb4nOCUwO0IFm638lHHG4BhRGC%2BNcQpoy1a0z4fi2seOaRJfSo%2BM734%2FrNnpWq74gojyt2zMm86h9LCTH3n84acBOxfQFM8xWdkopmeoclz63VjJTRaW%2F%2Be1BbM2W9Ty%2Fzx9Q3kEVS3PU0EzCYZvz44n1OGm8gGKbgbPE0KASKKtHch%2BYdhyQb4vp0avy2%2BICyEeMe%2F%2FVjVA5rVd5QLt6HeXsQ94Knb4BCdVVNS49p0OI8jHk5eMmqnh7GdsxmcfbEjoMDOhGDitoDhAV7OWvZfpNe19vCosIqhr5rEJQwPVS%2B%2BT8y7GBAz19zg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002A76D0E63E0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 16:20:25,934 ERROR   wandb-upload_1:28508 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9492'}
2024-03-13 16:20:25,934 ERROR   wandb-upload_1:28508 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 16:20:25,949 ERROR   wandb-upload_2:28508 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/6nygko79/config.yaml?Expires=1710404416&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=H3Si3QogMZsrrPJuivdmjYUx2ME197pRFathG0YX7RZmO9jLKH5Phup7uUnmSaXwkeejg7%2Fq2E89M08qLmtLjk3vHJtG2ypdXnIvlN0ysxsEHAgLW32PJCP0FenwhMjl2wcDAs9fj5lfruUFYloKms5doYKK4dxGaRQI%2FwmmCVrknSkB%2FTRrHbb1A40DOMJLMLYyu1s6rzKgZfBhW3CA%2BndlXiCsN1wk4H2j9fL0oZj8LUycTz7f%2FbuFaQi2Kn5HER4uAzgv3y5nAg5mU%2BcByODpQ1sFCbjCRG5amGZE%2BbSCy3cR2BYd9kR2c%2BRN6fCGnUphiW0dZERSuh79%2B6h41A%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/6nygko79/config.yaml?Expires=1710404416&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=H3Si3QogMZsrrPJuivdmjYUx2ME197pRFathG0YX7RZmO9jLKH5Phup7uUnmSaXwkeejg7%2Fq2E89M08qLmtLjk3vHJtG2ypdXnIvlN0ysxsEHAgLW32PJCP0FenwhMjl2wcDAs9fj5lfruUFYloKms5doYKK4dxGaRQI%2FwmmCVrknSkB%2FTRrHbb1A40DOMJLMLYyu1s6rzKgZfBhW3CA%2BndlXiCsN1wk4H2j9fL0oZj8LUycTz7f%2FbuFaQi2Kn5HER4uAzgv3y5nAg5mU%2BcByODpQ1sFCbjCRG5amGZE%2BbSCy3cR2BYd9kR2c%2BRN6fCGnUphiW0dZERSuh79%2B6h41A%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002A76D0E5B10>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 16:20:25,949 ERROR   wandb-upload_2:28508 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '456'}
2024-03-13 16:20:25,949 ERROR   wandb-upload_2:28508 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 16:20:26,174 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:20:26,174 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:20:26,311 ERROR   wandb-upload_3:28508 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/6nygko79/output.log?Expires=1710404416&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=O9GZNsik3tYHJZzp%2BDYLqxCfAegDLmtTJFM7uVK9zQAWBy1VFaR%2FD69HgpMEtE27Dzr1jYj5w35Hrq3VFFdjX3IaDgnxV0Aalifa0OkSIYH7wBmZGToUiC4tv4A1Nvue%2BeuhijOlYn95vnIRMgKc5WwrKYT8hQYco64G5v4PHkIqN2VYi1O4EQCS33w9nBRuL7GmBzagJ%2BR8vUgL63B8aXpkAVfRNT6pYxl29hEXKeYe9qeDI1E4y3b2wcJ7n0oJ5QMeylrwPJDfgH1k%2BTQC9vBsU2GqXB%2F6fWgNRZnlYkY2jSX956Ugs7E%2FRik7NhC95ZT%2FqxJkMKPakRBGsZwjJw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/6nygko79/output.log?Expires=1710404416&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=O9GZNsik3tYHJZzp%2BDYLqxCfAegDLmtTJFM7uVK9zQAWBy1VFaR%2FD69HgpMEtE27Dzr1jYj5w35Hrq3VFFdjX3IaDgnxV0Aalifa0OkSIYH7wBmZGToUiC4tv4A1Nvue%2BeuhijOlYn95vnIRMgKc5WwrKYT8hQYco64G5v4PHkIqN2VYi1O4EQCS33w9nBRuL7GmBzagJ%2BR8vUgL63B8aXpkAVfRNT6pYxl29hEXKeYe9qeDI1E4y3b2wcJ7n0oJ5QMeylrwPJDfgH1k%2BTQC9vBsU2GqXB%2F6fWgNRZnlYkY2jSX956Ugs7E%2FRik7NhC95ZT%2FqxJkMKPakRBGsZwjJw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002A76D2869B0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 16:20:26,311 ERROR   wandb-upload_5:28508 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/6nygko79/wandb-summary.json?Expires=1710404417&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=rJ%2Fl2KPF72cA7PxrHzfX4B%2FGOO6jdRupipMm6UG3B9Pz9Ot9p5wX4JOBzZ1V%2BGBg823Z9m8gNJiLv9cTqcQbfNgG918eh7yHiMSMfW3gUInqN4EwBHXfWSP3O37DiCQKGVTvMqXGm7XZ2SAY6sBJvX1ToUHccBZ8Q6CGtYsaIThDCH7pEcSpab2SWZI1jDXuXqEEvMT205VSgrxVDJr%2B3N%2BLvIfww5nqtNexXo3vwRA2k7bYSBOVCz2dj%2Ba01uQ4D7nmnsykzEwmEtLg8RU0NqrUoYA9OGS9QoHhNAm8z2A29gQ7WH9v3OfdRa%2FLZ1ojua6uqLkei2bRoFXgncS8hw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/6nygko79/wandb-summary.json?Expires=1710404417&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=rJ%2Fl2KPF72cA7PxrHzfX4B%2FGOO6jdRupipMm6UG3B9Pz9Ot9p5wX4JOBzZ1V%2BGBg823Z9m8gNJiLv9cTqcQbfNgG918eh7yHiMSMfW3gUInqN4EwBHXfWSP3O37DiCQKGVTvMqXGm7XZ2SAY6sBJvX1ToUHccBZ8Q6CGtYsaIThDCH7pEcSpab2SWZI1jDXuXqEEvMT205VSgrxVDJr%2B3N%2BLvIfww5nqtNexXo3vwRA2k7bYSBOVCz2dj%2Ba01uQ4D7nmnsykzEwmEtLg8RU0NqrUoYA9OGS9QoHhNAm8z2A29gQ7WH9v3OfdRa%2FLZ1ojua6uqLkei2bRoFXgncS8hw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002A76D284A30>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 16:20:26,311 ERROR   wandb-upload_3:28508 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1392'}
2024-03-13 16:20:26,311 ERROR   wandb-upload_5:28508 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '206'}
2024-03-13 16:20:26,311 ERROR   wandb-upload_3:28508 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 16:20:26,311 ERROR   wandb-upload_5:28508 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 16:20:26,573 ERROR   wandb-upload_4:28508 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/princeporch/uncategorized/6nygko79/requirements.txt?Expires=1710404417&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=VrEVdssvdTVAhf94qi%2BVGWC%2Bi4wFgS2kKFdEE82LcmXLJWd8RUM7uZuoFRj3P%2FZId4kRUKkI7mGLlSVijDHh%2FhUyNmwBSox5e1ENxYolP1deiT9y0byGOrFKT%2BVcsnkatKO0Fth9uI1YH2g2DpATXL8k%2FBivFNgaN14pYSHDr5t8E8W2FSKxEyJU0s0VOcHaz%2BHcmZ%2FCDoxTVHVFl%2BIHurqqdKbEBZvkerPgoELulIXbQ8%2F8iDp2ErsfkwjcS3cN5iqH79EQo95YLtBr0YevlLk2h1pQgO%2BnmmoS881VPsaazh3K5hmrZGL9CP6n8rWxefiVZvDhrYr006KCfKWAkg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/princeporch/uncategorized/6nygko79/requirements.txt?Expires=1710404417&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=VrEVdssvdTVAhf94qi%2BVGWC%2Bi4wFgS2kKFdEE82LcmXLJWd8RUM7uZuoFRj3P%2FZId4kRUKkI7mGLlSVijDHh%2FhUyNmwBSox5e1ENxYolP1deiT9y0byGOrFKT%2BVcsnkatKO0Fth9uI1YH2g2DpATXL8k%2FBivFNgaN14pYSHDr5t8E8W2FSKxEyJU0s0VOcHaz%2BHcmZ%2FCDoxTVHVFl%2BIHurqqdKbEBZvkerPgoELulIXbQ8%2F8iDp2ErsfkwjcS3cN5iqH79EQo95YLtBr0YevlLk2h1pQgO%2BnmmoS881VPsaazh3K5hmrZGL9CP6n8rWxefiVZvDhrYr006KCfKWAkg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002A76D287940>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-03-13 16:20:26,573 ERROR   wandb-upload_4:28508 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3463'}
2024-03-13 16:20:26,573 ERROR   wandb-upload_4:28508 [internal_api.py:upload_file():2560] upload_file response body: 
2024-03-13 16:20:27,186 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:20:27,186 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:20:28,202 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 16:20:28,202 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:20:28,202 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:20:29,216 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:20:29,216 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:20:30,228 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:20:30,229 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:20:31,231 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:20:31,231 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:20:32,246 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:20:32,246 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:20:33,247 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:20:33,247 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:20:33,248 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: status_report
2024-03-13 16:20:34,252 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:20:34,252 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:20:35,256 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:20:35,257 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: poll_exit
2024-03-13 16:20:36,260 DEBUG   HandlerThread:28508 [handler.py:handle_request():144] handle_request: poll_exit
2024-03-13 16:20:36,261 DEBUG   SenderThread:28508 [sender.py:send_request():407] send_request: poll_exit
